export type Language = "en" | "ja";

export type LocalizedText = {
  en: string;
  ja: string;
};

export type Program = {
  category: LocalizedText;
  name: LocalizedText;
  audience: LocalizedText;
  useCase: LocalizedText;
  officialLink: string;
  adminAction: LocalizedText;
  tags: LocalizedText[];
  priority: "High" | "Medium" | "Watch";
};

export const priorityLabels: Record<Program["priority"], LocalizedText> = {
  High: { en: "High", ja: "重要" },
  Medium: { en: "Medium", ja: "標準" },
  Watch: { en: "Watch", ja: "要確認" },
};

export const programs: Program[] = [
  {
    category: { en: "Portal", ja: "検索ポータル" },
    name: { en: "J-Net21 Support Information Headline", ja: "J-Net21 支援情報ヘッドライン" },
    audience: { en: "National, prefecture, and municipality support information", ja: "国・都道府県・市区町村の支援情報を探す事業者" },
    useCase: { en: "Search subsidies, grants, loans, and events by region and category.", ja: "地域やカテゴリ別に補助金、助成金、融資、イベントを検索できます。" },
    officialLink: "https://j-net21.smrj.go.jp/snavi/",
    adminAction: { en: "Check monthly for local programs.", ja: "地域別の制度を毎月確認してください。" },
    tags: [{ en: "local", ja: "地方自治体" }, { en: "search", ja: "検索" }, { en: "all", ja: "全般" }],
    priority: "High",
  },
  {
    category: { en: "Portal", ja: "検索ポータル" },
    name: { en: "Mirasapo Plus", ja: "ミラサポplus" },
    audience: { en: "SMEs looking for METI and SME Agency subsidy guidance", ja: "経済産業省・中小企業庁系の補助金を確認したい中小企業" },
    useCase: { en: "Track major national SME grant updates, examples, and guides.", ja: "主要な国の中小企業向け補助金、活用事例、申請ガイドを確認できます。" },
    officialLink: "https://mirasapo-plus.go.jp/",
    adminAction: { en: "Check before each application cycle.", ja: "各公募サイクルの前に必ず確認してください。" },
    tags: [{ en: "national", ja: "国" }, { en: "search", ja: "検索" }, { en: "sme", ja: "中小企業" }],
    priority: "High",
  },
  {
    category: { en: "Portal", ja: "検索ポータル" },
    name: { en: "JGrants", ja: "Jグランツ" },
    audience: { en: "Businesses submitting government grant applications online", ja: "補助金を電子申請する事業者" },
    useCase: { en: "Electronic applications for many subsidy programs.", ja: "多くの補助金をオンラインで申請するための政府ポータルです。" },
    officialLink: "https://www.jgrants-portal.go.jp/",
    adminAction: { en: "Confirm G Biz ID and submission route.", ja: "GビズIDと申請経路を事前に確認してください。" },
    tags: [{ en: "application", ja: "申請" }, { en: "g-biz", ja: "GビズID" }],
    priority: "High",
  },
  {
    category: { en: "SME Investment", ja: "中小企業投資" },
    name: { en: "SME Labor-Saving Investment Subsidy", ja: "中小企業省力化投資補助金" },
    audience: { en: "SMEs facing labor shortages", ja: "人手不足に対応したい中小企業" },
    useCase: { en: "Catalog products, equipment, systems, automation, and labor-saving investment.", ja: "カタログ掲載製品、設備、システム、自動化など省力化投資に使えます。" },
    officialLink: "https://shoryokuka.smrj.go.jp/",
    adminAction: { en: "Check current call and whether catalog or general type fits.", ja: "現在の公募と、カタログ型・一般型のどちらが合うか確認してください。" },
    tags: [{ en: "automation", ja: "自動化" }, { en: "equipment", ja: "設備" }, { en: "labor shortage", ja: "人手不足" }],
    priority: "High",
  },
  {
    category: { en: "SME Investment", ja: "中小企業投資" },
    name: { en: "Monodzukuri Productivity Subsidy", ja: "ものづくり・商業・サービス生産性向上促進補助金" },
    audience: { en: "SMEs investing in productivity, products, services, or processes", ja: "生産性向上、新製品、新サービス、工程改善に取り組む中小企業" },
    useCase: { en: "Equipment, process improvement, services, and production capability.", ja: "設備投資、工程改善、新サービス、製造能力強化などに使えます。" },
    officialLink: "https://portal.monodukuri-hojo.jp/",
    adminAction: { en: "Check schedule, public guidelines, and G Biz ID readiness.", ja: "公募日程、公募要領、GビズIDの準備状況を確認してください。" },
    tags: [{ en: "equipment", ja: "設備" }, { en: "productivity", ja: "生産性" }, { en: "manufacturing", ja: "ものづくり" }],
    priority: "High",
  },
  {
    category: { en: "IT / AI", ja: "IT・AI" },
    name: { en: "Digitalization / AI Introduction Subsidy", ja: "デジタル化・AI導入補助金" },
    audience: { en: "SMEs adopting registered IT or AI tools", ja: "登録済みのIT・AIツールを導入する中小企業" },
    useCase: { en: "Software, AI, POS, ERP, accounting, security, and digital tools.", ja: "ソフトウェア、AI、POS、ERP、会計、セキュリティなどに使えます。" },
    officialLink: "https://it-shien.smrj.go.jp/",
    adminAction: { en: "Use registered IT support providers and tools.", ja: "登録IT導入支援事業者と登録ツールを利用してください。" },
    tags: [{ en: "ai", ja: "AI" }, { en: "software", ja: "ソフトウェア" }, { en: "digital", ja: "デジタル" }],
    priority: "High",
  },
  {
    category: { en: "Small Business", ja: "小規模事業者" },
    name: { en: "Small Business Sustainability Subsidy", ja: "小規模事業者持続化補助金" },
    audience: { en: "Small-scale businesses", ja: "小規模事業者" },
    useCase: { en: "Websites, flyers, trade fairs, store improvements, and sales expansion.", ja: "ウェブサイト、チラシ、展示会、店舗改装、販路開拓などに使えます。" },
    officialLink: "https://r6.jizokukahojokin.info/",
    adminAction: { en: "Confirm chamber of commerce or society of commerce route.", ja: "商工会議所地区か商工会地区か、申請ルートを確認してください。" },
    tags: [{ en: "marketing", ja: "販路開拓" }, { en: "website", ja: "ウェブサイト" }, { en: "sales", ja: "販売" }],
    priority: "High",
  },
  {
    category: { en: "New Business", ja: "新規事業" },
    name: { en: "New Business Expansion Subsidy", ja: "中小企業新事業進出補助金" },
    audience: { en: "SMEs entering a new business field", ja: "新しい事業分野へ進出する中小企業" },
    useCase: { en: "Buildings, machinery, systems, advertising, and training for new business entry.", ja: "建物、機械装置、システム、広告、研修など新規事業進出に使えます。" },
    officialLink: "https://shinjigyou-shinshutsu.smrj.go.jp/",
    adminAction: { en: "Check current public offering schedule and documents.", ja: "現在の公募スケジュールと申請書類を確認してください。" },
    tags: [{ en: "new business", ja: "新規事業" }, { en: "diversification", ja: "多角化" }, { en: "investment", ja: "投資" }],
    priority: "High",
  },
  {
    category: { en: "Succession / M&A", ja: "事業承継・M&A" },
    name: { en: "Business Succession and M&A Subsidy", ja: "事業承継・M&A補助金" },
    audience: { en: "SMEs doing succession, M&A, PMI, or rechallenge", ja: "事業承継、M&A、PMI、再チャレンジに取り組む中小企業" },
    useCase: { en: "Expert fees, PMI, equipment for succession, and disposal costs.", ja: "専門家費用、PMI、承継後の設備、廃業費用などに使えます。" },
    officialLink: "https://shoukei-mahojokin.go.jp/",
    adminAction: { en: "Check active round and eligible framework.", ja: "現在の公募回と対象枠を確認してください。" },
    tags: [{ en: "succession", ja: "事業承継" }, { en: "m&a", ja: "M&A" }, { en: "pmi", ja: "PMI" }],
    priority: "High",
  },
  {
    category: { en: "Growth", ja: "成長投資" },
    name: { en: "SME Growth Acceleration Subsidy", ja: "中小企業成長加速化補助金" },
    audience: { en: "SMEs aiming for JPY 10B sales", ja: "売上高100億円を目指す中小企業" },
    useCase: { en: "Large investment, exports, and regional supply-chain impact.", ja: "大規模投資、輸出、地域サプライチェーン強化などに使われます。" },
    officialLink: "https://growth-100-oku.smrj.go.jp/",
    adminAction: { en: "Check next call; 100 Oku Declaration may be required.", ja: "次回公募と100億宣言の要否を確認してください。" },
    tags: [{ en: "growth", ja: "成長" }, { en: "exports", ja: "輸出" }, { en: "large investment", ja: "大規模投資" }],
    priority: "Watch",
  },
  {
    category: { en: "Growth", ja: "成長投資" },
    name: { en: "Large-Scale Growth Investment Subsidy", ja: "中堅・中小成長投資補助金" },
    audience: { en: "Mid-sized and SME companies planning large investments and wage increases", ja: "大規模投資と賃上げに取り組む中堅・中小企業" },
    useCase: { en: "Large equipment, new sites, labor-saving investment, business expansion, and wage-linked growth plans.", ja: "大型設備、新拠点、省力化投資、事業拡大、賃上げを伴う成長投資に使えます。" },
    officialLink: "https://seichotoushi-hojo.jp/",
    adminAction: { en: "Check whether the next call is open and whether the investment scale and wage requirements fit.", ja: "次回公募の有無、投資規模、賃上げ要件を確認してください。" },
    tags: [{ en: "growth", ja: "成長" }, { en: "wages", ja: "賃上げ" }, { en: "large investment", ja: "大規模投資" }],
    priority: "Watch",
  },
  {
    category: { en: "Energy", ja: "省エネ" },
    name: { en: "Energy Saving / Non-Fossil Conversion Subsidy", ja: "省エネ・非化石転換補助金" },
    audience: { en: "Companies investing in energy saving", ja: "省エネ設備や非化石転換に投資する企業" },
    useCase: { en: "Equipment replacement, fuel conversion, EMS, and site energy saving.", ja: "設備更新、燃料転換、EMS、工場・事業所の省エネに使えます。" },
    officialLink: "https://syouenehojyokin.sii.or.jp/",
    adminAction: { en: "Check application type and deadline.", ja: "申請類型と締切を確認してください。" },
    tags: [{ en: "energy", ja: "省エネ" }, { en: "decarbonization", ja: "脱炭素" }, { en: "equipment", ja: "設備" }],
    priority: "High",
  },
  {
    category: { en: "R&D", ja: "研究開発" },
    name: { en: "Go-Tech R&D Support", ja: "成長型中小企業等研究開発支援事業 / Go-Tech" },
    audience: { en: "SMEs doing advanced R&D with partners", ja: "連携体で高度な研究開発に取り組む中小企業" },
    useCase: { en: "R&D, prototype development, and commercialization.", ja: "研究開発、試作品開発、事業化に向けた取り組みに使えます。" },
    officialLink: "https://www.chusho.meti.go.jp/keiei/sapoin/",
    adminAction: { en: "Check annual call and partner requirements.", ja: "年度ごとの公募と連携体要件を確認してください。" },
    tags: [{ en: "research", ja: "研究" }, { en: "prototype", ja: "試作" }, { en: "innovation", ja: "イノベーション" }],
    priority: "Medium",
  },
  {
    category: { en: "Export", ja: "輸出" },
    name: { en: "New Exporters Support Program / JETRO", ja: "新規輸出1万者支援プログラム / JETRO" },
    audience: { en: "SMEs starting or expanding exports", ja: "輸出を開始・拡大したい中小企業" },
    useCase: { en: "Expert support and overseas market entry.", ja: "専門家支援や海外市場開拓に活用できます。" },
    officialLink: "https://www.jetro.go.jp/services/new_export/",
    adminAction: { en: "Combine with other grants where allowed.", ja: "他の補助金と併用できるか確認してください。" },
    tags: [{ en: "export", ja: "輸出" }, { en: "overseas", ja: "海外" }, { en: "jetro", ja: "JETRO" }],
    priority: "Medium",
  },
  {
    category: { en: "Export / IP", ja: "海外展開・知財" },
    name: { en: "Overseas Application Support Subsidy", ja: "中小企業等海外展開支援事業費補助金（海外出願支援事業）" },
    audience: { en: "SMEs filing patents, utility models, designs, or trademarks overseas", ja: "海外で特許・実用新案・意匠・商標を出願する中小企業" },
    useCase: { en: "Foreign patent office fees, domestic and local attorney fees, translation, and other overseas filing costs.", ja: "外国特許庁への出願手数料、国内・現地代理人費用、翻訳費用などに使えます。" },
    officialLink: "https://www.jpo.go.jp/support/chusho/shien_gaikokusyutugan.html",
    adminAction: { en: "Apply through the prefectural SME support center or regional implementing organization.", ja: "都道府県等中小企業支援センターなど地域実施機関の公募を確認してください。" },
    tags: [{ en: "export", ja: "海外展開" }, { en: "ip", ja: "知財" }, { en: "patent", ja: "特許" }],
    priority: "Medium",
  },
  {
    category: { en: "Tokyo Local", ja: "東京都助成金" },
    name: { en: "Tokyo New Product / New Technology Development Grant", ja: "新製品・新技術開発助成事業" },
    audience: { en: "Tokyo SMEs and founders developing new products, technologies, or services", ja: "都内で新製品・新技術・新サービスの研究開発を行う中小企業・創業予定者" },
    useCase: { en: "Materials, machinery, outsourcing, IP filing, expert guidance, and direct labor for R&D prototypes.", ja: "原材料、機械装置、委託・外注、産業財産権、専門家指導、研究開発の直接人件費などに使えます。" },
    officialLink: "https://www.tokyo-kosha.or.jp/support/josei/jigyo/shinseihin.html",
    adminAction: { en: "Tokyo-only program; check the yearly application window and JGrants requirements.", ja: "東京都内向けです。年度ごとの受付期間とJグランツ要件を確認してください。" },
    tags: [{ en: "tokyo", ja: "東京都" }, { en: "r&d", ja: "研究開発" }, { en: "prototype", ja: "試作" }],
    priority: "Watch",
  },
  {
    category: { en: "Employer Grants", ja: "雇用関係助成金" },
    name: { en: "MHLW Employer Grant Portal", ja: "厚生労働省 雇用関係助成金ポータル" },
    audience: { en: "Employers", ja: "事業主" },
    useCase: { en: "Master page for all employment-related grants.", ja: "雇用関係助成金の一覧と最新情報を確認する入口です。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/index.html",
    adminAction: { en: "Start here for latest MHLW grant notices.", ja: "厚労省の最新通知はここから確認してください。" },
    tags: [{ en: "employment", ja: "雇用" }, { en: "mhlw", ja: "厚労省" }, { en: "portal", ja: "ポータル" }],
    priority: "High",
  },
  {
    category: { en: "Employment / Wages", ja: "雇用・賃金" },
    name: { en: "Career Up Subsidy", ja: "キャリアアップ助成金" },
    audience: { en: "Employers with fixed-term, part-time, dispatched, or other non-regular workers", ja: "有期契約、パート、派遣など非正規雇用労働者を雇用する事業主" },
    useCase: { en: "Regular conversion, wage-rule revision, bonus/retirement systems, and longer hours.", ja: "正社員化、賃金規定改定、賞与・退職金制度、労働時間延長などに使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
    adminAction: { en: "File the plan before the action; confirm foreign worker eligibility with Labor Bureau.", ja: "実施前に計画届が必要です。外国人労働者は労働局で対象可否を確認してください。" },
    tags: [{ en: "employees", ja: "従業員" }, { en: "wages", ja: "賃金" }, { en: "foreign employees", ja: "外国人従業員" }],
    priority: "High",
  },
  {
    category: { en: "Training", ja: "人材育成" },
    name: { en: "Human Resource Development Subsidy", ja: "人材開発支援助成金" },
    audience: { en: "Employers training workers", ja: "従業員に職業訓練を実施する事業主" },
    useCase: { en: "Training expenses and wages during job-related training or reskilling.", ja: "職務関連訓練、リスキリング、訓練中の賃金助成などに使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/d01-1.html",
    adminAction: { en: "Best candidate for employee and foreign-employee training if course requirements fit.", ja: "従業員・外国人従業員研修の候補です。コース要件を確認してください。" },
    tags: [{ en: "training", ja: "研修" }, { en: "reskilling", ja: "リスキリング" }, { en: "foreign employees", ja: "外国人従業員" }],
    priority: "High",
  },
  {
    category: { en: "Retention / HR Systems", ja: "定着・人事制度" },
    name: { en: "Human Resource Securing Support Subsidy", ja: "人材確保等支援助成金" },
    audience: { en: "Employers improving HR management and retention", ja: "人材定着や雇用管理改善に取り組む事業主" },
    useCase: { en: "Employment management systems, care equipment, and retention improvements.", ja: "雇用管理制度、介護福祉機器、定着率改善などに使われます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000199292.html",
    adminAction: { en: "Open current course page from MHLW before planning.", ja: "計画前に厚労省の最新コースページを確認してください。" },
    tags: [{ en: "retention", ja: "定着" }, { en: "hr", ja: "人事" }, { en: "employees", ja: "従業員" }],
    priority: "Medium",
  },
  {
    category: { en: "Hiring", ja: "採用" },
    name: { en: "Trial Employment Subsidy", ja: "トライアル雇用助成金" },
    audience: { en: "Employers hiring eligible workers through approved routes", ja: "対象労働者をハローワーク等の紹介で試行雇用する事業主" },
    useCase: { en: "Trial hiring via Hello Work or approved referrals.", ja: "ハローワーク等の紹介による試行雇用に使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/trial_koyou.html",
    adminAction: { en: "Confirm target worker category and referral route.", ja: "対象労働者の区分と紹介経路を確認してください。" },
    tags: [{ en: "hiring", ja: "採用" }, { en: "hello work", ja: "ハローワーク" }, { en: "employees", ja: "従業員" }],
    priority: "Medium",
  },
  {
    category: { en: "Hiring", ja: "採用" },
    name: { en: "Labor Mobility Support Subsidy", ja: "労働移動支援助成金（早期雇入れ支援コース）" },
    audience: { en: "Employers hiring workers who must leave another company because of business downsizing or restructuring", ja: "事業規模縮小等により離職を余儀なくされた労働者を早期に雇い入れる事業主" },
    useCase: { en: "Support for early hiring of eligible displaced workers through approved routes.", ja: "対象となる離職者を早期に雇い入れる場合の支援に使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000082805_00007.html",
    adminAction: { en: "Confirm referral route, worker eligibility, and timing before hiring.", ja: "採用前に紹介経路、対象労働者、雇入れ時期の要件を確認してください。" },
    tags: [{ en: "hiring", ja: "採用" }, { en: "employees", ja: "従業員" }, { en: "re-employment", ja: "再就職" }],
    priority: "Medium",
  },
  {
    category: { en: "Employment Maintenance", ja: "雇用維持" },
    name: { en: "Industrial Employment Stabilization Subsidy", ja: "産業雇用安定助成金（雇用維持支援コース）" },
    audience: { en: "Employers maintaining employment through temporary transfer or related employment-stability measures", ja: "出向等により雇用維持を図る事業主" },
    useCase: { en: "Employment maintenance during business changes, temporary transfers, and stabilization measures.", ja: "事業環境の変化に伴う雇用維持、出向、雇用安定の取り組みに使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000082805_00008.html",
    adminAction: { en: "Check current MHLW course details because target periods and course names change.", ja: "対象期間やコース名が変わるため、厚労省の最新ページで確認してください。" },
    tags: [{ en: "employment", ja: "雇用" }, { en: "retention", ja: "雇用維持" }, { en: "employees", ja: "従業員" }],
    priority: "Medium",
  },
  {
    category: { en: "Wage Increase", ja: "賃上げ" },
    name: { en: "Business Improvement Subsidy", ja: "業務改善助成金" },
    audience: { en: "SMEs raising minimum wages", ja: "事業場内最低賃金を引き上げる中小企業" },
    useCase: { en: "Equipment, systems, and consulting tied to wage increases.", ja: "賃上げと連動した設備、システム、コンサルティングなどに使えます。" },
    officialLink: "https://www.mhlw.go.jp/gyomukaizen/",
    adminAction: { en: "Check prefecture wage and budget status.", ja: "都道府県別最低賃金と予算状況を確認してください。" },
    tags: [{ en: "wages", ja: "賃金" }, { en: "productivity", ja: "生産性" }, { en: "employees", ja: "従業員" }],
    priority: "High",
  },
  {
    category: { en: "Work-Life Balance", ja: "仕事と家庭の両立" },
    name: { en: "Work-Life Balance / Childcare Support Grants", ja: "両立支援等助成金" },
    audience: { en: "Employers supporting childcare, nursing care, leave, and return", ja: "育児・介護休業、復職、柔軟な働き方を支援する事業主" },
    useCase: { en: "Leave support, return-to-work systems, and flexible work.", ja: "休業取得、復職支援、柔軟な勤務制度などに使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kodomo/shokuba_kosodate/ryouritsu01/index.html",
    adminAction: { en: "Useful for retention and compliance.", ja: "人材定着と労務コンプライアンスに有用です。" },
    tags: [{ en: "childcare", ja: "育児" }, { en: "retention", ja: "定着" }, { en: "employees", ja: "従業員" }],
    priority: "Medium",
  },
  {
    category: { en: "Foreign Employees", ja: "外国人従業員" },
    name: { en: "Foreign Worker Employment Management Support", ja: "外国人雇用管理支援" },
    audience: { en: "Employers hiring foreign nationals", ja: "外国人を雇用する事業主" },
    useCase: { en: "Compliance, workplace management, and consultation.", ja: "在留資格に配慮した雇用管理、労働条件、相談支援の確認に使えます。" },
    officialLink: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000144964.html",
    adminAction: { en: "Mostly guidance; also search local foreign-talent grants.", ja: "主にガイダンスです。自治体の外国人材関連助成も併せて検索してください。" },
    tags: [{ en: "foreign employees", ja: "外国人従業員" }, { en: "compliance", ja: "コンプライアンス" }, { en: "hiring", ja: "採用" }],
    priority: "High",
  },
  {
    category: { en: "Foreign Company / Local Investment", ja: "外資系企業・地域投資" },
    name: { en: "JETRO Invest Japan", ja: "JETRO 対日投資支援" },
    audience: { en: "Foreign companies and Japan subsidiaries", ja: "外国企業および日本法人・子会社" },
    useCase: { en: "Market entry, setup, local incentives, and consultations.", ja: "日本進出、拠点設立、自治体インセンティブ、相談支援に使えます。" },
    officialLink: "https://www.jetro.go.jp/en/invest/",
    adminAction: { en: "Use for foreign-owned company support and local incentives.", ja: "外資系企業支援や地域インセンティブの入口として使ってください。" },
    tags: [{ en: "foreign company", ja: "外資系企業" }, { en: "local", ja: "地方自治体" }, { en: "jetro", ja: "JETRO" }],
    priority: "High",
  },
];

export const localSources: Array<[LocalizedText, LocalizedText, string]> = [
  [{ en: "Nationwide local search", ja: "全国の自治体検索" }, { en: "J-Net21 Support Information Headline", ja: "J-Net21 支援情報ヘッドライン" }, "https://j-net21.smrj.go.jp/snavi/"],
  [{ en: "Tokyo", ja: "東京都" }, { en: "Tokyo SME Support Center", ja: "東京都中小企業振興公社" }, "https://www.tokyo-kosha.or.jp/support/josei/"],
  [{ en: "Tokyo", ja: "東京都" }, { en: "Tokyo Bureau of Industrial and Labor Affairs", ja: "東京都産業労働局" }, "https://www.sangyo-rodo.metro.tokyo.lg.jp/"],
  [{ en: "Osaka", ja: "大阪府" }, { en: "Osaka business support", ja: "大阪府 経営支援" }, "https://www.pref.osaka.lg.jp/o110050/keieishien/index.html"],
  [{ en: "Aichi", ja: "愛知県" }, { en: "Aichi industry and business support", ja: "愛知県 産業政策" }, "https://www.pref.aichi.jp/soshiki/sangyo-seisaku/"],
  [{ en: "Fukuoka", ja: "福岡県" }, { en: "Fukuoka SME support", ja: "福岡県 中小企業支援" }, "https://www.pref.fukuoka.lg.jp/contents/chusho.html"],
  [{ en: "Hokkaido", ja: "北海道" }, { en: "Hokkaido SME support", ja: "北海道 中小企業支援" }, "https://www.pref.hokkaido.lg.jp/kz/csk/"],
  [{ en: "Regions", ja: "地域情報" }, { en: "JETRO regional information", ja: "JETRO 地域別情報" }, "https://www.jetro.go.jp/en/invest/region/"],
];

export const checklist: LocalizedText[] = [
  { en: "Confirm SME or small-business eligibility by industry, capital, employees, and affiliated companies.", ja: "業種、資本金、従業員数、関連会社をもとに中小企業・小規模事業者の該当性を確認する。" },
  { en: "Confirm current call, deadline, and whether application closes early.", ja: "現在の公募、締切、早期終了の可能性を確認する。" },
  { en: "Prepare G Biz ID Prime before the deadline.", ja: "締切前にGビズIDプライムを準備する。" },
  { en: "Prepare latest financials, tax certificates, quotes, specs, and vendor documents.", ja: "最新の決算書、納税証明書、見積書、仕様書、ベンダー資料を準備する。" },
  { en: "Do not order or contract before approval unless the program explicitly allows it.", ja: "制度が明確に認める場合を除き、交付決定前に発注・契約しない。" },
  { en: "Check wage increase, minimum wage, and reporting requirements.", ja: "賃上げ、最低賃金、報告義務の要件を確認する。" },
  { en: "Check double-subsidy restrictions for the same expense.", ja: "同じ経費に対する補助金の重複利用制限を確認する。" },
  { en: "Calendar post-award reporting for business results, wages, assets, and effect reports.", ja: "採択後の事業実績、賃金、資産、効果報告の期限をカレンダー管理する。" },
];
